print_file:
  target:
    entity:
      integration: ipp_print
      domain: sensor
  fields:
    path:
      required: true
      example: /config/www/report.pdf
      selector:
        text:
    document_format:
      example: application/pdf
      selector:
        text:
    job_name:
      example: report.pdf
      selector:
        text:
    copies:
      example: 1
      selector:
        number:
          min: 1
          max: 99
          mode: box
    sides:
      example: two-sided-long-edge
      selector:
        select:
          options:
            - one-sided
            - two-sided-long-edge
            - two-sided-short-edge
          translation_key: sides
    media:
      example: iso_a4_210x297mm
      selector:
        text:
    media_source:
      example: tray-1
      selector:
        text:
    color_mode:
      example: monochrome
      selector:
        text:
    quality:
      example: 4
      selector:
        number:
          min: 3
          max: 5
          step: 1
          mode: box
